CC=g++
CFLAGS=-g -Wall -Wextra -Werror

TARGETS=phub_peerid_hash cid_store_hash

all:$(TARGETS)

phub_peerid_hash: phub_peerid_hash.c

cid_store_hash: cid_store_hash.c

clean:
	$(RM) $(OBJS) $(DEPS) $(TARGETS)
