#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "$0 [start | restart | stop | test]"
    exit 1
fi

if [[ $1 == "start" ]]; then
    /home/maxingsong/opt/nginx-1.5.13/sbin/nginx
elif [[ $1 == "restart" ]]; then
    /home/maxingsong/opt/nginx-1.5.13/sbin/nginx -s reload
elif [[ $1 == "stop" ]]; then
    /home/maxingsong/opt/nginx-1.5.13/sbin/nginx -s quit
elif [[ $1 == "test" ]]; then
    /home/maxingsong/opt/nginx-1.5.13/sbin/nginx -t
else
    echo "$0 [start | restart | stop | test]"
fi
